### ISSUE TITLE
RC loading contract error message needs to be replaced

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#645]
Error message shows html and directs user to wrong email address (OLC address). @anderspeders to supply correct address.
![screen shot 2015-11-11 at 2 40 51 pm](https://cloud.githubusercontent.com/assets/14825437/11102490/798037fa-8882-11e5-9bb6-c8e15e3b511b.png)

**Comment by KaitlinCCSI** [comment]
Also, not sure why this error message showing, but if it is b/c it has been submitted to MT, then suggest that user should not be able to download Word doc version on advanced search page or contract view page until has been finalized through MT.

http://www.resourcecontracts.org/contract/ocds-591adf-LR1288985318RC/view

**Comment by charlesyoung** [comment]
@KaitlinCCSI this error occurs when the PDF Text hasn't been published. This occurs on other contracts where the PDF Text hasn't been published. 

![image](https://cloud.githubusercontent.com/assets/13888372/11420512/36e3db5c-9437-11e5-8bc9-7d244ce33035.png)

**Comment by anjesh** [comment]
This page content/messages need to be updated. Currently it says "We're sorry, there is a problem loading the contract. Please contact info-resourcecontracts@resourcegovernance.org to let us know, or check back later." when the contract text/pdf is not published. This needs to be changed.

When the text/pdf is not published, show this message
> "The contract text/pdf is not published yet. We are working to publish it soon. Contact us at info-resourcecontracts@resourcegovernance.org for more information."

When the is_ocr_review flag is set to false, then we are showing this message
> "We are currently processing the contract's PDF file, and a text version is not yet available."

If the pdf couldn't be shown for any other reason than above, the show this message
> "We're sorry, there is a problem loading the contract. Please contact info-resourcecontracts@resourcegovernance.org to let us know, or check back later."

**Comment by anderspeders** [comment]
A few corrections, then this should be ready to implement. 

@samCCSI @KaitlinCCSI: Any corrections to the text below before we go ahead with this?

When the text/pdf is not published, show this message
"The contract text or PDF has not been published yet. We are working to publish it soon. Please contact us at info-resourcecontracts@resourcegovernance.org for more information."

When the is_ocr_review flag is set to false, then we are showing this message
"We are currently processing the PDF contract in order to extract the text. The text version is not available yet. Please check again later or contact us at info-resourcecontracts@resourcegovernance.org for more information."

If the pdf couldn't be shown for any other reason than above, the show this message
"We are sorry. There is a problem loading the contract. Please contact info-resourcecontracts@resourcegovernance.org to let us know about the issue."

**Comment by KaitlinCCSI** [comment]
Is this message just for RC or also for OLC? (If also for OLC, then OLC email address should be used on OLC messages).

Re the messages, I would suggest:

![image](https://cloud.githubusercontent.com/assets/14825437/13121554/4c066a54-d578-11e5-891d-bb2349288a75.png)

**Comment by upasna01** [comment]
The issue have been fixed. Please review changes. The screenshot for the message is shown below.
![resourcecontracts org search contracts](https://cloud.githubusercontent.com/assets/11477899/13419132/f41e3c14-dfa3-11e5-9752-08bcd13fa20c.png)

**Comment by KaitlinCCSI** [comment]
Thanks. For OLC, though, the email needs to be info@openlandcontracts.org. Reopening so this can be changed on OLC only.

**Comment by upasna01** [comment]
Email in OLC have been changed, please review the change.
![rc](https://cloud.githubusercontent.com/assets/11477899/13493904/0e941f5c-e169-11e5-8680-3670f0469096.png)

**Comment by charlesyoung** [comment]
Two different error messages for the same issue. The text/PDF of below contract has not yet been published. 

![image](https://cloud.githubusercontent.com/assets/13888372/14012752/8f8e4b9e-f1b0-11e5-8645-dc386c8f4903.png)

![image](https://cloud.githubusercontent.com/assets/13888372/14012761/a1ccc7f4-f1b0-11e5-95a0-70ec3d169f58.png)

http://www.resourcecontracts.org/contract/ocds-591adf-LR9472538737RC/view#/text

**Comment by charlesyoung** [comment]
Still getting the 'We're sorry, there is a problem loading the contract. Please contact info-resourcecontracts@resourcegovernance.org to let us know, or check back later.' error when the text/pdf has not been published. 

http://www.resourcecontracts.org/contract/ocds-591adf-SL0498783225RC-1832/view

![image](https://cloud.githubusercontent.com/assets/13888372/14487530/5d070be4-0163-11e6-97c9-66ad01a4ea12.png)

**Comment by manishgs** [comment]
This bug is related to publishing workflow so It'll be fixed in issue #778
