### ISSUE TITLE
Scoping: Revisit the backend workflow with regards to publishing workflow.

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#778]
The current publishing workflow is confusing to many users, hence many bugs are reported due to the confusion in the workflow. We need to revisit the UX and the flow of the workflow. First we need to do the scoping and then move on with the changes. 

This should also address https://github.com/NRGI/resourcecontracts.org/issues/767

**Comment by anderspeders** [comment]
Agree that we need to deal with this, but let's focus on current issues scheduled in the sprint. If some ideas could be ready for sprint 14 that would be great.

**Comment by hello-deepak** [comment]
Here is [link](https://github.com/NRGI/resourcecontracts.org/wiki/Workflow-of-publishing-contract .) mock up for contract publishing workflow 

Please review and do provide feedback.

**Comment by charlesyoung** [comment]
Initial comments re the new publish contracts workflow. 

1. Should the 'Last Published Date' field not be left blank if not yet published rather than showing 'Not Published'?
2. What is the 'Comment' field for? 
3. How is the user notified that the text type needs to be completed? 

It's good to see that if the text type is "Needs Editing" or "Needs Full Transcription" the PDF text won't be published.

**Comment by SamCCSI** [comment]
I disagree with  "To complete Annotations, Metadata and PDF Text must be in published". Often the text will still be processing, but the user can annotate the PDF.

We have found that whenever we publish metadata, or annotations, we have to click "publish all" even where they display as "published." Not sure why this is needed - it might be a bug.

**Comment by hello-deepak** [comment]
[Here](https://github.com/NRGI/resourcecontracts.org/wiki/Workflow-of-publishing-contract) is updated Workflow of publishing contract .

@charlesyoung 

> Should the 'Last Published Date' field not be left blank if not yet published rather than showing 'Not Published'?

Yes 'Last Published Date' can be left blank if not yet published. I have updated the workflow.

> What is the 'Comment' field for?

Please see this issue https://github.com/NRGI/resourcecontracts.org/issues/106 .

> How is the user notified that the text type needs to be completed?

On completion of text extraction process, users are notified through email. And after that text type can be completed accordingly.

@SamCCSI 
I have updated workflow according to your comment.

 Let me know if you have any confusion.

**Comment by manishgs** [comment]
Please review updated contract publishing [workflow](http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1824)  on demond let us know your feedback.

For how workflow works. we have guide in [wiki](https://github.com/NRGI/resourcecontracts.org/wiki/Workflow-of-publishing-contract)

**Comment by SamCCSI** [comment]
Many thanks @manish I have just reviewed; I hope some of this is helpful.

- For metadata / text / annotations, What happens if I reject the text like in the screenshot by accident? Where do I click to have the text reinstated? I understand that if it needs to be reprocessed, I can click on "Text type" and then submit to MT.
![image](https://cloud.githubusercontent.com/assets/12913915/17824773/f1e8046a-6631-11e6-932e-3cf31b554887.png)

- "Text type" should be changed to "Text quality" or something more accurate.

- Are you going to get rid of the "show PDF" metadata category that currently regulates whether the text is shown? What will happen to the contracts that currently have show PDF text set to "No"? The majority of them will have "text type" set to "Needs full transcription" but I worry that some (especially in OLC) may be set to "text acceptable", but may be awaiting manual alteration by our interns and so are set to Show Pdf text = No.

- When I click "Complete" why does the window pop up asking for comments? If I am completing, it means there are no comments needed.
![image](https://cloud.githubusercontent.com/assets/12913915/17824799/1a1f3cb4-6632-11e6-92e2-d428113c1548.png)

- _"If any one of the above elements is edited, its state will change to 'draft'"_ – this makes the site hard to manage. Example: I research a contract on RC and see a typo in the annotation. I go into the backend and correct the typo. If I forget to then go back and click "Publish all" then this contract's annotations will no longer show on the site. (I will likely remember to do this but we have many annotators working in the system at the same time who may not remember).

- Related to the above, can we try to make the "Published" status more robust? E.g. there are times where the status of the contract metadata, text, and annotations all say "published", but I need to click "publish all" again before any recent changes are shown on the site. Perhaps that is what this new workflow does. If it labeled as published, then it should show all of the latest amendments. Otherwise it should be labeled as "draft".

- Annotations. To me it is confusing to have "draft" next to annotations when we haven't attempted to annotate yet. 
![image](https://cloud.githubusercontent.com/assets/12913915/17825234/d4c2c548-6634-11e6-8707-d7c598008e9b.png)
It is much more intuitive the way the system currently works. That is, it is blank, and there is an "Annotate" button. Then it is in "draft" until the annotate clicks complete and then publish. See screenshot of current system: 
![image](https://cloud.githubusercontent.com/assets/12913915/17825018/5287953c-6633-11e6-9c49-e78e17950fec.png)

- All comment functions (contract status, metadata, and annotations): Unfortunately we found that all of these comment functions take more time than simply emailing the uploader or annotator with a word document full of our comments. I'm passing this on as feedback and in case there are other ways to create a comment function for the site that is much simpler and requires many fewer clicks. cc @jedm @anderspeders

**Comment by manishgs** [comment]
@SamCCSI 
> For metadata / text / annotations, What happens if I reject the text like in the screenshot by accident? Where do I click to have the text reinstated? I understand that if it needs to be reprocessed, I can click on "Text type" and then submit to MT.

Reject status simply rejects metadata/text/annotations changes done by researcher. Here "Reject" status means simply change the status to "Reject" so that researcher see the Reject comment and do the necessary changes and status change to "complete".

> Are you going to get rid of the "show PDF" metadata category that currently regulates whether the text is shown? What will happen to the contracts that currently have show PDF text set to "No"? The majority of them will have "text type" set to "Needs full transcription" but I worry that some (especially in OLC) may be set to "text acceptable", but may be awaiting manual alteration by our interns and so are set to Show Pdf text = No.

Yes we'll remove the "Show pdf" from metadata. Now this functionality can be done from PDF Text publish/unpublish action. It'll not affect on already published/unpublished contracts but after implementing new workflow to publish a contract needs to follow new workflow (eg. need to change text type to "Acceptable")


> When I click "Complete" why does the window pop up asking for comments? If I am completing, it means there are no comments needed.

Comment is optional for  "Complete" and "Publish" status and only required for rejecting.

>"If any one of the above elements is edited, its state will change to 'draft'" – this makes the site hard to manage. Example: I research a contract on RC and see a typo in the annotation. I go into the backend and correct the typo. If I forget to then go back and click "Publish all" then this contract's annotations will no longer show on the site. (I will likely remember to do this but we have many annotators working in the system at the same time who may not remember).

If you make changes on specific metadata/text/annotation then you don't need to publish all. You can publish only specific metadata/text/annotation changes. In your your case annotations should show on the site. If there is any issue with this then let us know on which contract did you see that issue?

**Comment by manishgs** [comment]
> Annotations. To me it is confusing to have "draft" next to annotations when we haven't attempted to annotate yet. 

We'll have "Annotate" button if there is no annotations for the contract. and "Draft" if there is any added/changes in annotations.

**Comment by SamCCSI** [comment]
Thanks for all those responses @manishgs. Just a couple of follow-up questions:

- I'm not clear on the answer to my first question. If I reject text, how change the text status to complete?

- "Comment is optional for "Complete" and "Publish" status and only required for rejecting." I think we should **not** have a comment feature for "Complete" and "Publish". This won't be used and adds another click to the process.

**Comment by manishgs** [comment]
@SamCCSI 
> I'm not clear on the answer to my first question. If I reject text, how change the text status to complete?

If  Pdf text is rejected then you need to make changes on Pdf Text so that status change to "Draft" and you can complete and publish Text.

**Comment by hello-deepak** [comment]
Review the following changes in [demo](http://resourcecontracts-demo1.elasticbeanstalk.com/) site:
* Comment popup is removed from "Complete" and "Publish" status.
* "Text Type" is changed to "Text Quality".
* Annotate button appears if there is 0 annotation.
* Show pdf Text has been handled . It is not going affect already published  contracts. And show pdf text input  is also removed from contract form.

And let us know your feedback.

**Comment by SamCCSI** [comment]
@hello-deepak Looks good.

I have received one more request – from multiple annotators and reviewers.

Is it possible to make the structure of the back-end contract overview (eg http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1850) exactly the same as the edit page (http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1850/edit)?

Right now the overview page does not display all fields, and the order is different than it is in the edit page. This is confusing for users. It also means that reviewers have to click 'edit' just to check each field, rather than being able to check each field on the overview page.

**Comment by hello-deepak** [comment]
@SamCCSI 
Displaying of all metadata will covered in this https://github.com/NRGI/resourcecontracts.org/issues/937  issue .

Shall we deploy workflow in live site?

**Comment by charlesyoung** [comment]
@anjesh as discussed how do we communicate major updates, like this ticket, to the various country subsites before deploying?

**Comment by anjesh** [comment]
We could simply use mass emails (or use mailchimp like services) to update them about the major updates in the system. These major updates could be posted as blog or simply as email content, based on the size of the updates (whether we want to include screenshots in the update text or not). 

@charlesyoung are you maintaining the user documentation? 

We are thinking of deploying this new workflow to production on Tuesday, 30 Aug. Please let us know if there are any issues with regards to workflow latest by Aug 25 EOD. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
We will need to send out some form of communication either as an email or blog. @anjesh what is the preferred and most sustainable solution?

**Comment by anjesh** [comment]
I prefer blog post, as the post will always be accessible when needed and can also be referenced later, rather than email content. Also any improvements on the blog post could be made based on the need. I will start working on the blog post, and while emailing, we could have a teaser, linking to the blog post from there.

**Comment by charlesyoung** [comment]
Thanks @anjesh

**Comment by hello-deepak** [comment]
I think we can close this .

Here is the [link](https://blog.yipl.com.np/workflow-updated-in-resourcecontracts-to-ease-the-contract-publishing-process-7e7269fe3485#.lliu6wgha) of blog on Workflow  . Please go through it .

If you find any issue . Please create new one .

**Comment by SamCCSI** [comment]
I had to delete an annotation from an already published contract, but then there was no way to 'republish' the entire contract, and the annotation still appeared on the front end. So I unpublished the PDF text, thinking that I could then click publish again, and then the annotation updates would be incorporated.

Instead, I now cannot re-publish the PDF text. Can you explain how this is supposed to work, and also help me to re-publish this contract? Seems like we need to improve this in the workflow.

![image](https://cloud.githubusercontent.com/assets/12913915/20917621/d2a7fb12-bb92-11e6-85d2-4644e6836104.png)

Here is the link: http://resourcecontracts.elasticbeanstalk.com/contract/1134

**Comment by manishgs** [comment]
> ...and the annotation still appeared on the front end.

We've implemented cache for 5 min so you need to wait for 5 min  to see the changes on frontend.

You need to update **Text Quality** to **Acceptable** in order to publish pdf text. If other than **Acceptable** options are selected then publish/unpublish buttons will be hide and you can't publish pdf text.

Let us know if you have any confusion.

**Comment by SamCCSI** [comment]
@manishgs Thanks. If I change the text quality to acceptable, is there any risk we will lose the transcription work done by mechanical turk and then cleaned up by our interns?

**Comment by manishgs** [comment]
You can update text quality anytime. It just a status flag which will not affect transcription work.  You need to update text quality status to **Acceptable** after MTurk tasks are completed,

**Comment by SamCCSI** [comment]
Thanks @manishgs I just republished PDF text.

Unfortunately the deleted annotation for Outgrowers' program is still present on the front end for both of the contracts even though I deleted it. So maybe the cache is set to more than 5 mins?

http://www.openlandcontracts.org/contract/ocds-591adf-7497994880/view#/pdf
http://www.openlandcontracts.org/contract/ocds-591adf-7812180414/view#/pdf

http://resourcecontracts.elasticbeanstalk.com/contract/1133
http://resourcecontracts.elasticbeanstalk.com/contract/1134

**Comment by manishgs** [comment]
Can you please check again I've cleared the cache?

**Comment by SamCCSI** [comment]
@manishgs it is still there.

**Comment by SamCCSI** [comment]
The annotation is still there –– I started a new thread to deal with the issue of deleting annotations: https://github.com/NRGI/resourcecontracts.org/issues/1009
